apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etl-engine-module.fullname" . }}-config
data:
  conf.yaml: |- 
{{- if .Values.config_override }}
{{ .Values.config_override  | indent 4}}
{{- else }}
{{ tpl ( .Files.Get "files/conf.yaml" ) . | indent 4 }}
{{- end -}}